.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 8/4/10               \" TODO: fix date
.Dt openman 1
.Os Darwin
.Sh NAME
.Nm openman
.Nd display manual pages in ManOpen.app.
.Sh SYNOPSIS
.Nm
.Op Fl kb
.Op Fl m Ar path
.Op Fl M Ar path
.Op Fl f Ar file
.Op Ar section
.Op Ar name ...
.Sh DESCRIPTION
.Nm
is a command-line utility to open Unix man pages in ManOpen.app. The
syntax is generally the same as the
.Xr man 1
command, with an additional option to directly open files.
.Pp
.Nm
will open a page in ManOpen.app for every title given.  If a section
specifier is given,
.Nm
looks in that section of the manual for the given
.Ar titles.
.Ar Section
is typically an Arabic section number (
.Dq 1
for user commands,
.Dq 8
for administrative commands, etc), but it can be a named
section as well.  If
.Ar section
is omitted,
.Nm
searches all sections of the manual, giving preference to commands
over subroutines in system libraries, and printing the first section
it finds, if any.
.Pp
If the
.Fl k
flag is specified, then
.Xr apropos 1
mode is used, with each given title
used as an Apropos lookup in ManOpen.app instead of being opened as
an individual page.
.Pp
Normally, ManOpen.app is brought forward to be the active application
when messaged by openman (meaning Terminal.app will no longer be the
active application).  If the
.Fl b
flag is specfied, ManOpen.app not be forcibly be made active (i.e.
will stay in the background).
.Pp
The man search path can be specified with the
.Fl M
or
.Fl m
flag.  The search path is a colon (':') separated list of directories
in which manual subdirectories may be found; e.g.
.Dq /usr/local/man:/usr/share/man
\&.
.Hw MANPATH
If a search path is not supplied, the value of the environment variable
.Sq MANPATH
is used for the search path.  If that isn't set, ManOpen's
man path (as specified in the application's preferences) is used.
.Pp
A file can be directly specified with the
.Fl f
flag.  If it's an nroff source file, ManOpen's
.Dq Nroff command
(as set in
the applications's preferences) will be used to process the file,
otherwise ManOpen will open it directly.  The argument can be a full or
relative path.
.Pp
If you use the tcsh shell, you can set openman's completion settings to
be similar to
.Xr man 1
's, which causes it to complete using command names.
Add the following to your ~/.cshrc or ~/.tchrc:
.Pp
.Dl complete openman 'n/-M/d/' 'p/*/c/'
.Pp
.Sh ENVIRONMENT
.Bl -tag -width "MANPATH" -indent
.It Ev MANPATH
A colon-seperated list of paths to search for man pages.
.El
.Sh SEE ALSO
ManOpen.app,
.Xr man 1 ,
.Xr apropos 1 ,
.Xr whereis 1
.Sh AUTHOR
.An Carl Lindberg Aq lindberg@clindberg.org
.Pp
Please send any bug reports/suggestions.
